openapi: 3.0.0
info:
  title: "API сервер для проекта «Шесть городов»."
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  version: "1.0.0"
  contact:
    name: Mikalai Stsebunou

tags:
  - name: users
    description: Действия с пользователями.
  - name: offers
    description: Действия с предлложениями по аренде.
  - name: comments
    description: Действия с комментариями.
